include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/flutter_flow/**
    - lib/auth/**
    - lib/login/**
    - lib/pages/**
  errors:
    unused_import: warning
    unused_local_variable: warning

linter:
  rules:
    unnecessary_string_escapes: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false